### ISSUE TITLE
ssl handshake failed stream

### ISSUE THREAD

**Issue by Liuxins** [FISCO-BCOS/java-sdk-demo#144]
### 按照官网配置 版本2.8.0 服务器ubuntu 安装jdk11 
**下载运行脚本：1. curl -#LO https://github.com/FISCO-BCOS/FISCO-BCOS/releases/download/v2.8.0/build_chain.sh && chmod u+x build_chain.sh 
                          2. d ~/fisco && curl -LO https://github.com/FISCO-BCOS/console/releases/download/v2.8.0/download_console.sh && bash download_console.sh
证书配置正常，控制台正常启动，节点正常启动
后续 启动压测 进行在 java -cp 'conf/:lib/*:apps/*' org.fisco.bcos.sdk.demo.perf.PerformanceOk [count] [tps] [groupId] 这一步时报错 
报错内容如下

`SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/home/bench/java-sdk-demo/dist/lib/log4j-slf4j-impl-2.19.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
====== PerformanceOk trans, count: 0, qps:20000, groupId: 1
====== PerformanceOk test failed, error message: get Client failed, e: /github/home/.hunter/_Base/0ba8099/8cf628f/0b4fef9/Build/bcos-boostssl/Source/bcos-boostssl/websocket/WsService.cpp(223): Throw in function void bcos::boostssl::ws::WsService::syncConnectToEndpoints(bcos::boostssl::ws::EndPointsPtr)
Dynamic exception type: boost::wrapexcept<std::runtime_error>
std::exception::what: [ ssl handshake failed stream truncated:/127.0.0.1:20200,  ssl handshake failed stream truncated:/127.0.0.1:20201]

`

**Comment by kyonRay** [comment]
节点如果是2.8.0，Java sdk demo需要切换到main-2.0版本 :)
